name: main_thread_processor
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/billy1380/main_thread_processor

environment:
  sdk: ^3.1.3

dependencies:
  logging: ^1.2.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
